const actionTypes = {
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  LOGIN_FAIL: 'LOGIN_FAIL',
  REGISTER_SUCCESSFUL: 'REGISTER_SUCCESSFUL',
  REGISTER_FAIL: 'REGISTER_FAIL',
  LOGOUT: 'LOGOUT',
  GET_POST: 'GET_POST',
};

export default actionTypes;
